MvcProjeCamp/Controllers/HeadingController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeCamp.Controllers
{
    public class HeadingController : Controller
    {

        IHeadingService headingService = new HeadingManager(new EfHeadingDal());
        ICategoryService categoryService = new CategoryManager(new EfCategoryDal());
        IWriterService writerService = new WriterManager(new EfWriterDal());

        public ActionResult Index()
        {
            var values = headingService.GetList();
            return View(values);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> category = (from x in categoryService.GetList()
                                             select new SelectListItem
                                             {
                                                 Text = x.CategoryName,
                                                 Value = x.CategoryId.ToString()
                                             }).ToList();
            ViewBag.categories = category;

            List<SelectListItem> writer = (from x in writerService.GetList()
                                           select new SelectListItem
                                           {
                                               Text = x.WriterName + " " + x.WriterSurname,
                                               Value = x.WriterId.ToString()
                                           }).ToList();
            ViewBag.writers = writer;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            headingService.Add(heading);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id)
        {
            var value = headingService.GetById(id);
            value.HeadingStatus = false;
            headingService.Delete(value);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UpdateHeading(int id)
        {
            var value = headingService.GetById(id);

            List<SelectListItem> category = (from x in categoryService.GetList()
                                          select new SelectListItem
                                          {
                                              Text = x.CategoryName,
                                              Value = x.CategoryId.ToString()
                                          }).ToList();
            ViewBag.categories = category;

            List<SelectListItem> writer = (from x in writerService.GetList()
                                          select new SelectListItem
                                          {
                                              Text = x.WriterName + " " + x.WriterSurname,
                                              Value = x.WriterId.ToString()
                                          }).ToList();
            ViewBag.writers = writer;
            return View(value);
        }

        [HttpPost]
        public ActionResult UpdateHeading(Heading heading)
        {
            headingService.Update(heading);
            return RedirectToAction("Index");
        }

        public ActionResult HeadingByWriteWriter(int id)
        {
            var values = headingService.GetListByWriterId(id);
            return View(values);
        }
    }
}

MvcProjeCamp/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Başlık Ekleme</h2>
<br />

@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />

        @Html.Label("Tarih")
        @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingDate)
        <br />

        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.categories, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
        <br />

        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.writers, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterId)
        <br />

        <button class="btn btn-primary">Başlık Ekle</button>
    </div>
}

MvcProjeCamp/Views/Heading/HeadingByWriteWriter.cshtml
@model List<EntityLayer.Concrete.Heading>

@{
    ViewBag.Title = "HeadingByWriteWriter";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"> Oluşturduğu Başlıklar</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <!-- Timelime example  -->
                        @foreach (var item in Model)
                        {
                            <div class="row">
                                <div class="col-md-12">
                                    <!-- The time line -->
                                    <div class="timeline">
                                        <!-- timeline time label -->
                                        <div class="time-label">
                                            <span class="bg-success">@item.HeadingDate.ToString("dd-MMM-yyyy")</span>
                                        </div>
                                        <!-- /.timeline-label -->
                                        <!-- timeline item -->
                                        <div>
                                            <i class="fas fa-comment bg-yellow"></i>
                                            <div class="timeline-item">
                                                <h3 class="timeline-header"><a href="/Content/ContentByHeading/@item.WriterId">@item.HeadingName </a> @item.Writer.WriterName @item.Writer.WriterSurname</h3>
                                                <div class="timeline-body">
                                                    
                                                </div>
                                            </div>
                                        </div>
                                        <!-- END timeline item -->
                                    </div>
                                </div>
                                <!-- /.col -->
                            </div>
                        }
                    </div>
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjeCamp/Views/Heading/Index.cshtml
@model List<EntityLayer.Concrete.Heading>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    string color = "";
    string text = "";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Başlıklar</h1>
            </div>
            @*<div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Projects</li>
                    </ol>
                </div>*@
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Proje İşlemleri</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Başlık Adı
                        </th>
                        <th style="width: 10%">
                            Oluşturan Yazar
                        </th>
                        <th style="width: 20%" class="text-center">
                            Kategori
                        </th>
                        <th style="width: 5%">
                            Durum
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.HeadingId</td>
                            <td>
                                <a>@item.HeadingName</a>
                                <br />
                                <small>@item.HeadingDate.ToString("dd-MMM-yyyy")</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline">
                                        <img alt="Avatar" style="text-align: center" class="table-avatar" src="@item.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            @if (item.Category.CategoryName == "Dizi")
                            {
                                <td class="project-state">
                                    <span class="badge badge-dark">@item.Category.CategoryName</span>
                                </td>
                            }
                            else if (item.Category.CategoryName == "Film")
                            {
                                <td class="project-state">
                                    <span class="badge badge-primary">@item.Category.CategoryName</span>
                                </td>
                            }
                            else if (item.Category.CategoryName == "Kitap")
                            {
                                <td class="project-state">
                                    <span class="badge badge-info">@item.Category.CategoryName</span>
                                </td>
                            }
                            else if (item.Category.CategoryName == "Tiyatro")
                            {
                                <td class="project-state">
                                    <span class="badge badge-success">@item.Category.CategoryName</span>
                                </td>
                            }
                            else if (item.Category.CategoryName == "Yazılım")
                            {
                                <td class="project-state">
                                    <span class="badge badge-danger">@item.Category.CategoryName</span>
                                </td>
                            }
                            else if (item.Category.CategoryName == "Seyahat")
                            {
                                <td class="project-state">
                                    <span class="badge badge-warning">@item.Category.CategoryName</span>
                                </td>
                            }
                            @if (item.HeadingStatus == true)
                            {
                                <td style="padding-left:20px;">
                                    <span class="badge badge-success">Aktif</span>
                                </td>
                            }
                            else
                            {
                                <td style="padding-left:20px;">
                                    <span class="badge badge-danger">Pasif</span>
                                </td>
                            }

                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                    <i class="fas fa-folder">
                                    </i>
                                    Yazılar
                                </a>
                                <a class="btn btn-info btn-sm" href="/Heading/UpdateHeading/@item.HeadingId">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingId">
                                    <i class="fas fa-trash">
                                    </i>
                                    Sil
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

<a href="/Heading/AddHeading/" class="btn btn-primary">Yeni Başlık Ekle</a>

MvcProjeCamp/Views/Heading/UpdateHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "UpdateHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Başlık Güncelleme</h2>
<br />

@using (Html.BeginForm("UpdateHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HeadingId)

        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />

        @Html.Label("Tarih")
        @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingDate)
        <br />

        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.categories, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
        <br />

        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.writers, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterId)
        <br />

        <button class="btn btn-primary">Başlık Güncelle</button>
    </div>
}